sudo: false

language: php
 
php:
  - 7.2.9

install:
  - composer require php-coveralls/php-coveralls

before_script:
  - composer install --prefer-source --no-interaction

script: 
  - composer test-coverage

after_success:
  - php vendor/bin/coveralls -v