sudo: false

language: php
 
php:
  - 7.2

before_script:
  - composer install --prefer-source --no-interaction

script: 
  - composer test-coverage
  - composer build-phar

after_success:  
  - php vendor/bin/php-coveralls -v
  - php skeleton.phar hello-world